from __future__ import annotations

import os

from app.ingestion.parsers import parse_file
from app.integrations.github.client import GitHubClient
from app.models import Repository
from app.publication.helpers import locale_file_path, serialize_locale_file  # written by parallel agent


class GitHubAdapter:
    """Implements both SourceAdapter and PublicationAdapter for GitHub."""

    def __init__(self, token: str) -> None:
        self._client = GitHubClient(token)

    async def fetch_source_strings(self, repository: Repository) -> dict[str, str]:
        source_file = repository.source_file or ""
        filename = os.path.basename(source_file)
        content = await self._client.get_file_content(
            repo=repository.github_repo,
            path=source_file,
            ref=repository.default_branch,
        )
        result = parse_file(content, filename, repository.file_format)
        return {pk.key: pk.source_text for pk in result.keys}

    async def subscribe_to_changes(self, repository: Repository, callback) -> None:
        # GitHub push events arrive via webhook; subscription is handled at the
        # platform level (webhook registration), not per-call. No-op here.
        pass

    async def publish_translations(
        self,
        repository: Repository,
        translations_by_locale: dict[str, dict[str, str]],
        branch_name: str,
    ) -> str:
        base_sha = await self._client.get_branch_sha(
            repo=repository.github_repo,
            branch=repository.default_branch,
        )
        await self._client.create_branch(
            repo=repository.github_repo,
            branch=branch_name,
            base_sha=base_sha,
        )

        for locale, key_values in translations_by_locale.items():
            path = locale_file_path(repository, locale)
            serialized = serialize_locale_file(repository, locale, key_values)
            await self._client.upsert_file(
                repo=repository.github_repo,
                path=path,
                content=serialized,
                message=f"chore(i18n): update {locale} translations",
                branch=branch_name,
            )

        pr_url = await self._client.create_pull_request(
            repo=repository.github_repo,
            title=f"chore(i18n): translation update — {', '.join(sorted(translations_by_locale))}",
            body=(
                "Automated translation update generated by Clariti TMS.\n\n"
                f"Locales: {', '.join(sorted(translations_by_locale))}"
            ),
            head=branch_name,
            base=repository.default_branch,
        )
        return pr_url
