// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 *
 * Payload for `POST /api-keys`.
 *
 * Note: the new key always inherits the calling key's organization. The
 * callable does not accept an `org_id` field — any such field in the body
 * is ignored, not honored, to prevent cross-tenant privilege escalation.
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ApiKeyCreated
 *
 * Returned only once at creation time — includes the raw key.
 */
export type ApiKeyCreated = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Org Admin
     */
    is_org_admin: boolean;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Raw Key
     */
    raw_key: string;
};

/**
 * ApiKeyRead
 */
export type ApiKeyRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Org Admin
     */
    is_org_admin: boolean;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Organization Id
     */
    organization_id: string;
};

/**
 * AppSettingsRead
 */
export type AppSettingsRead = {
    /**
     * Evaluate Temperature
     */
    evaluate_temperature: number;
    /**
     * Fallback Chain
     */
    fallback_chain: Array<string>;
    /**
     * Has Anthropic Key
     */
    has_anthropic_key: boolean;
    /**
     * Has Deepl Key
     */
    has_deepl_key: boolean;
    /**
     * Has Openai Key
     */
    has_openai_key: boolean;
    /**
     * Has Openrouter Key
     */
    has_openrouter_key: boolean;
    /**
     * Ollama Host
     */
    ollama_host: string | null;
    /**
     * Openrouter Model
     */
    openrouter_model: string;
    /**
     * Primary Provider
     */
    primary_provider: string;
    /**
     * Translate Temperature
     */
    translate_temperature: number;
};

/**
 * AppSettingsUpdate
 *
 * Partial-update body — every field is optional.
 *
 * Note the distinction between "field omitted" (no-op) and "field set to
 * empty string" (clear the encrypted column). Use ``exclude_unset=True``
 * on the server to make that split, not ``exclude_none``.
 */
export type AppSettingsUpdate = {
    /**
     * Anthropic Api Key
     */
    anthropic_api_key?: string | null;
    /**
     * Deepl Api Key
     */
    deepl_api_key?: string | null;
    /**
     * Evaluate Temperature
     */
    evaluate_temperature?: number | null;
    /**
     * Fallback Chain
     */
    fallback_chain?: Array<string> | null;
    /**
     * Ollama Host
     */
    ollama_host?: string | null;
    /**
     * Openai Api Key
     */
    openai_api_key?: string | null;
    /**
     * Openrouter Api Key
     */
    openrouter_api_key?: string | null;
    /**
     * Openrouter Model
     */
    openrouter_model?: string | null;
    /**
     * Primary Provider
     */
    primary_provider?: string | null;
    /**
     * Translate Temperature
     */
    translate_temperature?: number | null;
};

/**
 * BatchApproveResult
 */
export type BatchApproveResult = {
    /**
     * Approved
     */
    approved: number;
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Skipped
     */
    skipped: number;
};

/**
 * BatchDetail
 *
 * GET /batches/{id} — the BatchRead fields plus a computed stats block.
 */
export type BatchDetail = {
    /**
     * Component
     */
    component: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Mt Model
     */
    mt_model: string | null;
    /**
     * Mt Prompt Version
     */
    mt_prompt_version: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Ran At
     */
    ran_at: string | null;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Screen
     */
    screen: string | null;
    stats: BatchStats;
    /**
     * Status
     */
    status: string;
};

/**
 * BatchRead
 */
export type BatchRead = {
    /**
     * Component
     */
    component: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Mt Model
     */
    mt_model: string | null;
    /**
     * Mt Prompt Version
     */
    mt_prompt_version: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Ran At
     */
    ran_at: string | null;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Screen
     */
    screen: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * BatchRejectResult
 */
export type BatchRejectResult = {
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Rejected
     */
    rejected: number;
    /**
     * Skipped
     */
    skipped: number;
};

/**
 * BatchStats
 */
export type BatchStats = {
    /**
     * Approved
     */
    approved: number;
    /**
     * Needs Review
     */
    needs_review: number;
    /**
     * Total Keys
     */
    total_keys: number;
    /**
     * Translated
     */
    translated: number;
};

/**
 * BatchStatus
 */
export type BatchStatus = 'pending' | 'mt_running' | 'mt_complete' | 'needs_review' | 'approved' | 'published';

/**
 * BatchTrigger
 */
export type BatchTrigger = {
    /**
     * Provider
     */
    provider?: string;
};

/**
 * BatchTriggerResult
 */
export type BatchTriggerResult = {
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Status
     */
    status: string;
};

/**
 * Body_post_preview_api_v1_imports_preview_post
 */
export type BodyPostPreviewApiV1ImportsPreviewPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Format
     *
     * Wire format. 'xlsx' or 'xliff'. If omitted, auto-detected from the filename extension (.xlf / .xliff -> xliff, otherwise xlsx).
     */
    format?: 'xlsx' | 'xliff' | null;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * Body_upload_screenshot_api_v1_keys__key_id__screenshots_post
 */
export type BodyUploadScreenshotApiV1KeysKeyIdScreenshotsPost = {
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BulkTriggerResult
 */
export type BulkTriggerResult = {
    /**
     * Queued
     */
    queued: number;
    /**
     * Skipped
     */
    skipped: number;
};

/**
 * ComponentContextCreate
 */
export type ComponentContextCreate = {
    /**
     * Component
     */
    component: string;
    /**
     * Default Max Length
     */
    default_max_length?: number | null;
    /**
     * Default Risk Class
     */
    default_risk_class?: string;
    /**
     * Description
     */
    description: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Screen
     */
    screen?: string | null;
};

/**
 * ComponentContextRead
 */
export type ComponentContextRead = {
    /**
     * Component
     */
    component: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Default Max Length
     */
    default_max_length: number | null;
    /**
     * Default Risk Class
     */
    default_risk_class: string;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Screen
     */
    screen: string | null;
};

/**
 * ComponentContextUpdate
 */
export type ComponentContextUpdate = {
    /**
     * Component
     */
    component?: string | null;
    /**
     * Default Max Length
     */
    default_max_length?: number | null;
    /**
     * Default Risk Class
     */
    default_risk_class?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Screen
     */
    screen?: string | null;
};

/**
 * ExportCreate
 */
export type ExportCreate = {
    /**
     * Format
     *
     * Wire format. 'xlsx' returns the Phase 5 Excel workbook; 'xliff' returns an XLIFF 1.2 document for LSP exchange.
     */
    format?: 'xlsx' | 'xliff';
    /**
     * Locales
     *
     * BCP-47 locales, e.g. ['fr-FR','de-DE']
     */
    locales: Array<string>;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Sample Size
     *
     * Bootstrap-sampling knob. When set, rows are re-ordered by descending risk class (human_only > high_risk > standard > auto_publish) and limited to this count *per locale*. Used by the bootstrap wizard to export 50 highest-risk strings for native-speaker review.
     */
    sample_size?: number | null;
    /**
     * Status Filter
     *
     * Optional translation status filter (e.g. 'needs_review'). Omit for all rows.
     */
    status_filter?: string | null;
};

/**
 * GlossaryTermCreate
 */
export type GlossaryTermCreate = {
    /**
     * Case Sensitive
     */
    case_sensitive?: boolean;
    /**
     * Do Not Translate
     */
    do_not_translate?: boolean;
    /**
     * Locale
     */
    locale: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Source Term
     */
    source_term: string;
    /**
     * Target Term
     */
    target_term: string;
};

/**
 * GlossaryTermRead
 */
export type GlossaryTermRead = {
    /**
     * Case Sensitive
     */
    case_sensitive: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string | null;
    /**
     * Do Not Translate
     */
    do_not_translate: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Source Term
     */
    source_term: string;
    /**
     * Target Term
     */
    target_term: string;
};

/**
 * GlossaryTermUpdate
 */
export type GlossaryTermUpdate = {
    /**
     * Case Sensitive
     */
    case_sensitive?: boolean | null;
    /**
     * Do Not Translate
     */
    do_not_translate?: boolean | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Target Term
     */
    target_term?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportCommitResponse
 */
export type ImportCommitResponse = {
    /**
     * Applied Changes Count
     */
    applied_changes_count: number;
    /**
     * Committed At
     */
    committed_at: string | null;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Rollback Expires At
     */
    rollback_expires_at: string | null;
    /**
     * Skipped Count
     */
    skipped_count: number;
    /**
     * Status
     */
    status: string;
};

/**
 * ImportConflicts
 *
 * Conflict breakdown — source/translation changed since export.
 */
export type ImportConflicts = {
    /**
     * Details
     */
    details: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Source Changed
     */
    source_changed: number;
    /**
     * Translation Modified Externally
     */
    translation_modified_externally: number;
};

/**
 * ImportCounts
 *
 * Per-action row counts in a dry-run summary (``_summary_to_dict`` counts).
 */
export type ImportCounts = {
    /**
     * Approve
     */
    approve: number;
    /**
     * Edit
     */
    edit: number;
    /**
     * Needs More Context
     */
    needs_more_context: number;
    /**
     * Reject
     */
    reject: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Unknown
     */
    unknown: number;
};

/**
 * ImportDryRunSummary
 *
 * The ``dry_run_summary`` payload returned inside a preview response.
 *
 * Mirrors ``_summary_to_dict``. ``validation_errors`` / ``action_plan`` are
 * lists of per-row dicts (display-only on the client), kept loosely typed.
 */
export type ImportDryRunSummary = {
    /**
     * Action Plan
     */
    action_plan: Array<{
        [key: string]: unknown;
    }>;
    conflicts: ImportConflicts;
    counts: ImportCounts;
    /**
     * Export Timestamp
     */
    export_timestamp: string | null;
    /**
     * Format
     */
    format?: string | null;
    /**
     * Locales
     */
    locales: Array<string>;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Schema Version
     */
    schema_version: string;
    /**
     * Total Rows
     */
    total_rows: number;
    /**
     * Validation Error Count
     */
    validation_error_count: number;
    /**
     * Validation Errors
     */
    validation_errors: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ImportPreviewResponse
 */
export type ImportPreviewResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
    summary: ImportDryRunSummary;
};

/**
 * ImportRollbackResponse
 */
export type ImportRollbackResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * IngestRequest
 */
export type IngestRequest = {
    /**
     * Auto Translate
     *
     * Assemble batches and queue MT for any newly-draft translations.
     */
    auto_translate?: boolean;
    /**
     * Content
     *
     * Raw file contents.
     */
    content: string;
    /**
     * Format
     *
     * One of: android-xml, flat-json, flutter-arb, i18next, icu, ios-strings, ios-stringsdict, ios-xcstrings
     */
    format: string;
    /**
     * On Conflict
     *
     * Conflict policy when a key already exists. Only 'update_source' is supported today.
     */
    on_conflict?: string;
    /**
     * Path
     *
     * Original file path. Used for component inference.
     */
    path: string;
};

/**
 * IngestResult
 */
export type IngestResult = {
    /**
     * Batches
     */
    batches: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Created
     */
    created: number;
    /**
     * Format
     */
    format: string;
    /**
     * Keys
     */
    keys: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Parsed
     */
    parsed: number;
    /**
     * Path
     */
    path: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Unchanged
     */
    unchanged: number;
    /**
     * Updated
     */
    updated: number;
};

/**
 * KeyDetail
 *
 * GET /keys/{id} — the KeyRead fields plus the key's translations.
 */
export type KeyDetail = {
    /**
     * Component
     */
    component?: string | null;
    /**
     * Context
     */
    context?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * File Format
     */
    file_format?: string | null;
    /**
     * Has Structural Tags
     */
    has_structural_tags?: boolean;
    /**
     * Icu Shape
     */
    icu_shape?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Key
     */
    key: string;
    /**
     * Max Length
     */
    max_length: number | null;
    /**
     * Placeholders
     */
    placeholders?: Array<string>;
    /**
     * Plural Format
     */
    plural_format: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Risk Class
     */
    risk_class: string;
    /**
     * Screen
     */
    screen?: string | null;
    /**
     * Source Text
     */
    source_text: string;
    /**
     * String Type
     */
    string_type: string | null;
    /**
     * Translations
     */
    translations: Array<TranslationRead>;
};

/**
 * KeyRead
 */
export type KeyRead = {
    /**
     * Component
     */
    component?: string | null;
    /**
     * Context
     */
    context?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * File Format
     */
    file_format?: string | null;
    /**
     * Has Structural Tags
     */
    has_structural_tags?: boolean;
    /**
     * Icu Shape
     */
    icu_shape?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Key
     */
    key: string;
    /**
     * Max Length
     */
    max_length: number | null;
    /**
     * Placeholders
     */
    placeholders?: Array<string>;
    /**
     * Plural Format
     */
    plural_format: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Risk Class
     */
    risk_class: string;
    /**
     * Screen
     */
    screen?: string | null;
    /**
     * Source Text
     */
    source_text: string;
    /**
     * String Type
     */
    string_type: string | null;
};

/**
 * KeyUpdate
 */
export type KeyUpdate = {
    /**
     * Context
     */
    context?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Max Length
     */
    max_length?: number | null;
    /**
     * Risk Class
     */
    risk_class?: string | null;
    /**
     * Source Text
     */
    source_text?: string | null;
};

/**
 * ListResponse[ApiKeyRead]
 */
export type ListResponseApiKeyRead = {
    /**
     * Items
     */
    items: Array<ApiKeyRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[BatchRead]
 */
export type ListResponseBatchRead = {
    /**
     * Items
     */
    items: Array<BatchRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[ComponentContextRead]
 */
export type ListResponseComponentContextRead = {
    /**
     * Items
     */
    items: Array<ComponentContextRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[GlossaryTermRead]
 */
export type ListResponseGlossaryTermRead = {
    /**
     * Items
     */
    items: Array<GlossaryTermRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[KeyRead]
 */
export type ListResponseKeyRead = {
    /**
     * Items
     */
    items: Array<KeyRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[LocaleConfigRead]
 */
export type ListResponseLocaleConfigRead = {
    /**
     * Items
     */
    items: Array<LocaleConfigRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[MtRunRead]
 */
export type ListResponseMtRunRead = {
    /**
     * Items
     */
    items: Array<MtRunRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[OrgRead]
 */
export type ListResponseOrgRead = {
    /**
     * Items
     */
    items: Array<OrgRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[ProjectRead]
 */
export type ListResponseProjectRead = {
    /**
     * Items
     */
    items: Array<ProjectRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[RepositoryRead]
 */
export type ListResponseRepositoryRead = {
    /**
     * Items
     */
    items: Array<RepositoryRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[ScreenshotRead]
 */
export type ListResponseScreenshotRead = {
    /**
     * Items
     */
    items: Array<ScreenshotRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[TranslationHistoryRead]
 */
export type ListResponseTranslationHistoryRead = {
    /**
     * Items
     */
    items: Array<TranslationHistoryRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[TranslationRead]
 */
export type ListResponseTranslationRead = {
    /**
     * Items
     */
    items: Array<TranslationRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * ListResponse[UserRead]
 */
export type ListResponseUserRead = {
    /**
     * Items
     */
    items: Array<UserRead>;
    /**
     * Total
     */
    total?: number | null;
};

/**
 * LocaleConfigActivationResult
 *
 * Response shape for `POST /locale-configs?fan_out=true`.
 *
 * Returned alongside the created/found `locale_config` row so the UI can
 * render an immediate success state ("Seeded 247 drafts · Bootstrap →").
 */
export type LocaleConfigActivationResult = {
    /**
     * Already Existed
     */
    already_existed: boolean;
    /**
     * Drafts Created
     */
    drafts_created: number;
    locale_config: LocaleConfigRead;
};

/**
 * LocaleConfigCreate
 */
export type LocaleConfigCreate = {
    /**
     * Formality
     */
    formality?: string;
    /**
     * Is Bootstrapped
     */
    is_bootstrapped?: boolean;
    /**
     * Locale
     */
    locale: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Register
     */
    register?: string | null;
};

/**
 * LocaleConfigRead
 */
export type LocaleConfigRead = {
    /**
     * Bootstrap State
     */
    bootstrap_state?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Formality
     */
    formality: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Activated
     */
    is_activated: boolean;
    /**
     * Is Bootstrapped
     */
    is_bootstrapped: boolean;
    /**
     * Locale
     */
    locale: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Register
     */
    register?: string | null;
};

/**
 * LocaleConfigUpdate
 */
export type LocaleConfigUpdate = {
    /**
     * Bootstrap State
     */
    bootstrap_state?: {
        [key: string]: unknown;
    } | null;
    /**
     * Formality
     */
    formality?: string | null;
    /**
     * Is Activated
     */
    is_activated?: boolean | null;
    /**
     * Is Bootstrapped
     */
    is_bootstrapped?: boolean | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Register
     */
    register?: string | null;
};

/**
 * MtRunRead
 *
 * One row from the `mt_runs` audit table.
 *
 * Powers the Phase 6 key-detail MT-run inspector. One row per LLM call —
 * primary attempt, retry, fallback. Full prompt + output text are
 * included so reviewers can dig into a specific translation's provenance.
 */
export type MtRunRead = {
    /**
     * Batch Id
     */
    batch_id: string | null;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Model
     */
    model: string;
    /**
     * Output Text
     */
    output_text: string;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Prompt Text
     */
    prompt_text: string;
    /**
     * Prompt Version
     */
    prompt_version: string;
    /**
     * Ran At
     */
    ran_at: string;
    /**
     * String Count
     */
    string_count: number | null;
    /**
     * Validator Errors
     */
    validator_errors: {
        [key: string]: unknown;
    } | null;
    /**
     * Validators Passed
     */
    validators_passed: boolean | null;
};

/**
 * OrgCreate
 */
export type OrgCreate = {
    /**
     * Admin Email
     */
    admin_email?: string | null;
    /**
     * Admin Name
     */
    admin_name?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * OrgRead
 */
export type OrgRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * OrgUpdate
 */
export type OrgUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Source Locale
     */
    source_locale?: string;
    /**
     * Style Guide
     */
    style_guide?: string | null;
    /**
     * Target Locales
     */
    target_locales?: Array<string>;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Source Locale
     */
    source_locale: string;
    /**
     * Style Guide
     */
    style_guide: string | null;
    /**
     * Target Locales
     */
    target_locales: Array<string>;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Source Locale
     */
    source_locale?: string | null;
    /**
     * Style Guide
     */
    style_guide?: string | null;
    /**
     * Target Locales
     */
    target_locales?: Array<string> | null;
};

/**
 * PublishResult
 *
 * POST /publications/repositories/{id}/publish.
 *
 * ``status`` is "ok" (PR opened) or "no_op" (nothing approved to publish);
 * ``pr_url`` is None on no_op. ``detail`` is only present on no_op, so it is
 * optional here.
 */
export type PublishResult = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Locale
     */
    locale: string | null;
    /**
     * Pr Url
     */
    pr_url: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * PublishToOtaResult
 *
 * POST /publications/repositories/{id}/publish-to-ota.
 */
export type PublishToOtaResult = {
    /**
     * Locale
     */
    locale: string | null;
    /**
     * Published
     */
    published: number;
    /**
     * Status
     */
    status: string;
};

/**
 * RepositoryCreate
 */
export type RepositoryCreate = {
    /**
     * Contentful Env
     */
    contentful_env?: string | null;
    /**
     * Contentful Space Id
     */
    contentful_space_id?: string | null;
    /**
     * Contentful Token
     */
    contentful_token?: string | null;
    /**
     * Contentful Webhook Secret
     */
    contentful_webhook_secret?: string | null;
    /**
     * Context Notes
     */
    context_notes?: string | null;
    /**
     * Default Branch
     */
    default_branch?: string;
    /**
     * File Format
     */
    file_format: string;
    /**
     * Github Installation Id
     */
    github_installation_id?: number | null;
    /**
     * Github Path
     */
    github_path?: string | null;
    /**
     * Github Repo
     */
    github_repo?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Plural Convention
     */
    plural_convention?: string;
    /**
     * Source File
     */
    source_file?: string | null;
    /**
     * Webhook Secret
     */
    webhook_secret?: string | null;
};

/**
 * RepositoryRead
 *
 * Public read schema.
 *
 * Secret columns are NEVER returned by value. We expose three booleans
 * (`has_webhook_secret`, `has_contentful_token`, `has_contentful_webhook_secret`)
 * so clients can show "Secret configured" UI without ever receiving the
 * ciphertext or plaintext.
 */
export type RepositoryRead = {
    /**
     * Contentful Env
     */
    contentful_env: string | null;
    /**
     * Contentful Space Id
     */
    contentful_space_id: string | null;
    /**
     * Context Notes
     */
    context_notes: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Default Branch
     */
    default_branch: string;
    /**
     * File Format
     */
    file_format: string;
    /**
     * Github Installation Id
     */
    github_installation_id: number | null;
    /**
     * Github Path
     */
    github_path: string | null;
    /**
     * Github Repo
     */
    github_repo: string | null;
    /**
     * Has Contentful Token
     */
    has_contentful_token?: boolean;
    /**
     * Has Contentful Webhook Secret
     */
    has_contentful_webhook_secret?: boolean;
    /**
     * Has Webhook Secret
     */
    has_webhook_secret?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Plural Convention
     */
    plural_convention: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Source File
     */
    source_file: string | null;
};

/**
 * RepositoryUpdate
 */
export type RepositoryUpdate = {
    /**
     * Contentful Env
     */
    contentful_env?: string | null;
    /**
     * Contentful Space Id
     */
    contentful_space_id?: string | null;
    /**
     * Contentful Token
     */
    contentful_token?: string | null;
    /**
     * Contentful Webhook Secret
     */
    contentful_webhook_secret?: string | null;
    /**
     * Context Notes
     */
    context_notes?: string | null;
    /**
     * Default Branch
     */
    default_branch?: string | null;
    /**
     * File Format
     */
    file_format?: string | null;
    /**
     * Github Installation Id
     */
    github_installation_id?: number | null;
    /**
     * Github Path
     */
    github_path?: string | null;
    /**
     * Github Repo
     */
    github_repo?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Platform
     */
    platform?: string | null;
    /**
     * Plural Convention
     */
    plural_convention?: string | null;
    /**
     * Source File
     */
    source_file?: string | null;
    /**
     * Webhook Secret
     */
    webhook_secret?: string | null;
};

/**
 * ScreenshotRead
 *
 * Wire-format Screenshot. Used by both upload (201) and list responses.
 */
export type ScreenshotRead = {
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Key Id
     */
    key_id: string;
    /**
     * Storage Url
     */
    storage_url: string;
    /**
     * Uploaded At
     */
    uploaded_at: string;
};

/**
 * TranslationHistoryRead
 *
 * One row from the `translation_history` audit log.
 *
 * Written by the Postgres `record_translation_history()` trigger on every
 * UPDATE of `translations` (see migration `0001` + `0006`). The actor
 * identity (`changed_by`, `change_source`) comes from session-level GUCs
 * set by `app.core.database.set_request_attribution`.
 */
export type TranslationHistoryRead = {
    /**
     * Change Note
     */
    change_note: string | null;
    /**
     * Change Source
     */
    change_source: string | null;
    /**
     * Changed At
     */
    changed_at: string;
    /**
     * Changed By
     */
    changed_by: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * New Status
     */
    new_status: string | null;
    /**
     * New Value
     */
    new_value: string | null;
    /**
     * Prev Status
     */
    prev_status: string | null;
    /**
     * Prev Value
     */
    prev_value: string | null;
    /**
     * Translation Id
     */
    translation_id: string;
};

/**
 * TranslationRead
 */
export type TranslationRead = {
    /**
     * Back Translation
     */
    back_translation: string | null;
    /**
     * Back Translation Similarity
     */
    back_translation_similarity: number | null;
    /**
     * Batch Id
     */
    batch_id: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Key Id
     */
    key_id: string;
    /**
     * Locale
     */
    locale: string;
    /**
     * Mt Model
     */
    mt_model: string | null;
    /**
     * Mt Value
     */
    mt_value: string | null;
    /**
     * Qa Accuracy
     */
    qa_accuracy: number | null;
    /**
     * Qa Consistency
     */
    qa_consistency: number | null;
    /**
     * Qa Issue
     */
    qa_issue?: string | null;
    /**
     * Qa Naturalness
     */
    qa_naturalness: number | null;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    /**
     * Reviewer Action
     */
    reviewer_action: string | null;
    /**
     * Reviewer Notes
     */
    reviewer_notes?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Value
     */
    value: string | null;
};

/**
 * TranslationStatus
 */
export type TranslationStatus = 'draft' | 'mt_proposed' | 'needs_review' | 'needs_more_context' | 'approved' | 'rejected' | 'published';

/**
 * TranslationUpdate
 */
export type TranslationUpdate = {
    /**
     * Reviewer Action
     */
    reviewer_action?: string | null;
    /**
     * Reviewer Notes
     */
    reviewer_notes?: string | null;
    status?: TranslationStatus | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Assigned Locales
     */
    assigned_locales?: Array<string>;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role?: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Assigned Locales
     */
    assigned_locales: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Organization Id
     */
    organization_id: string | null;
    /**
     * Role
     */
    role: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WebhookAck
 */
export type WebhookAck = {
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Status
     */
    status: string;
};

export type ListApiKeysApiV1ApiKeysGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/api-keys';
};

export type ListApiKeysApiV1ApiKeysGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseApiKeyRead;
};

export type ListApiKeysApiV1ApiKeysGetResponse = ListApiKeysApiV1ApiKeysGetResponses[keyof ListApiKeysApiV1ApiKeysGetResponses];

export type CreateApiKeyApiV1ApiKeysPostData = {
    body: ApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/api-keys';
};

export type CreateApiKeyApiV1ApiKeysPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyApiV1ApiKeysPostError = CreateApiKeyApiV1ApiKeysPostErrors[keyof CreateApiKeyApiV1ApiKeysPostErrors];

export type CreateApiKeyApiV1ApiKeysPostResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreated;
};

export type CreateApiKeyApiV1ApiKeysPostResponse = CreateApiKeyApiV1ApiKeysPostResponses[keyof CreateApiKeyApiV1ApiKeysPostResponses];

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/api-keys/{key_id}';
};

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteError = RevokeApiKeyApiV1ApiKeysKeyIdDeleteErrors[keyof RevokeApiKeyApiV1ApiKeysKeyIdDeleteErrors];

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteResponse = RevokeApiKeyApiV1ApiKeysKeyIdDeleteResponses[keyof RevokeApiKeyApiV1ApiKeysKeyIdDeleteResponses];

export type GetAppSettingsApiV1AppSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/app-settings';
};

export type GetAppSettingsApiV1AppSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: AppSettingsRead;
};

export type GetAppSettingsApiV1AppSettingsGetResponse = GetAppSettingsApiV1AppSettingsGetResponses[keyof GetAppSettingsApiV1AppSettingsGetResponses];

export type UpdateAppSettingsApiV1AppSettingsPatchData = {
    body: AppSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/app-settings';
};

export type UpdateAppSettingsApiV1AppSettingsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAppSettingsApiV1AppSettingsPatchError = UpdateAppSettingsApiV1AppSettingsPatchErrors[keyof UpdateAppSettingsApiV1AppSettingsPatchErrors];

export type UpdateAppSettingsApiV1AppSettingsPatchResponses = {
    /**
     * Successful Response
     */
    200: AppSettingsRead;
};

export type UpdateAppSettingsApiV1AppSettingsPatchResponse = UpdateAppSettingsApiV1AppSettingsPatchResponses[keyof UpdateAppSettingsApiV1AppSettingsPatchResponses];

export type ListBatchesApiV1BatchesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Locale
         */
        locale?: string | null;
        /**
         * Status
         */
        status?: BatchStatus | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/batches';
};

export type ListBatchesApiV1BatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBatchesApiV1BatchesGetError = ListBatchesApiV1BatchesGetErrors[keyof ListBatchesApiV1BatchesGetErrors];

export type ListBatchesApiV1BatchesGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseBatchRead;
};

export type ListBatchesApiV1BatchesGetResponse = ListBatchesApiV1BatchesGetResponses[keyof ListBatchesApiV1BatchesGetResponses];

export type GetBatchApiV1BatchesBatchIdGetData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/batches/{batch_id}';
};

export type GetBatchApiV1BatchesBatchIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBatchApiV1BatchesBatchIdGetError = GetBatchApiV1BatchesBatchIdGetErrors[keyof GetBatchApiV1BatchesBatchIdGetErrors];

export type GetBatchApiV1BatchesBatchIdGetResponses = {
    /**
     * Successful Response
     */
    200: BatchDetail;
};

export type GetBatchApiV1BatchesBatchIdGetResponse = GetBatchApiV1BatchesBatchIdGetResponses[keyof GetBatchApiV1BatchesBatchIdGetResponses];

export type ApproveBatchApiV1BatchesBatchIdApprovePostData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/batches/{batch_id}/approve';
};

export type ApproveBatchApiV1BatchesBatchIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveBatchApiV1BatchesBatchIdApprovePostError = ApproveBatchApiV1BatchesBatchIdApprovePostErrors[keyof ApproveBatchApiV1BatchesBatchIdApprovePostErrors];

export type ApproveBatchApiV1BatchesBatchIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: BatchApproveResult;
};

export type ApproveBatchApiV1BatchesBatchIdApprovePostResponse = ApproveBatchApiV1BatchesBatchIdApprovePostResponses[keyof ApproveBatchApiV1BatchesBatchIdApprovePostResponses];

export type ListMtRunsApiV1BatchesBatchIdMtRunsGetData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/batches/{batch_id}/mt-runs';
};

export type ListMtRunsApiV1BatchesBatchIdMtRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMtRunsApiV1BatchesBatchIdMtRunsGetError = ListMtRunsApiV1BatchesBatchIdMtRunsGetErrors[keyof ListMtRunsApiV1BatchesBatchIdMtRunsGetErrors];

export type ListMtRunsApiV1BatchesBatchIdMtRunsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseMtRunRead;
};

export type ListMtRunsApiV1BatchesBatchIdMtRunsGetResponse = ListMtRunsApiV1BatchesBatchIdMtRunsGetResponses[keyof ListMtRunsApiV1BatchesBatchIdMtRunsGetResponses];

export type RejectBatchApiV1BatchesBatchIdRejectPostData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/batches/{batch_id}/reject';
};

export type RejectBatchApiV1BatchesBatchIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectBatchApiV1BatchesBatchIdRejectPostError = RejectBatchApiV1BatchesBatchIdRejectPostErrors[keyof RejectBatchApiV1BatchesBatchIdRejectPostErrors];

export type RejectBatchApiV1BatchesBatchIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: BatchRejectResult;
};

export type RejectBatchApiV1BatchesBatchIdRejectPostResponse = RejectBatchApiV1BatchesBatchIdRejectPostResponses[keyof RejectBatchApiV1BatchesBatchIdRejectPostResponses];

export type TriggerMtApiV1BatchesBatchIdTriggerMtPostData = {
    body: BatchTrigger;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/batches/{batch_id}/trigger-mt';
};

export type TriggerMtApiV1BatchesBatchIdTriggerMtPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerMtApiV1BatchesBatchIdTriggerMtPostError = TriggerMtApiV1BatchesBatchIdTriggerMtPostErrors[keyof TriggerMtApiV1BatchesBatchIdTriggerMtPostErrors];

export type TriggerMtApiV1BatchesBatchIdTriggerMtPostResponses = {
    /**
     * Successful Response
     */
    200: BatchTriggerResult;
};

export type TriggerMtApiV1BatchesBatchIdTriggerMtPostResponse = TriggerMtApiV1BatchesBatchIdTriggerMtPostResponses[keyof TriggerMtApiV1BatchesBatchIdTriggerMtPostResponses];

export type CreateExportApiV1ExportsPostData = {
    body: ExportCreate;
    path?: never;
    query?: never;
    url: '/api/v1/exports';
};

export type CreateExportApiV1ExportsPostErrors = {
    /**
     * Project not found in caller's organization.
     */
    404: unknown;
    /**
     * Invalid status filter or empty locales.
     */
    422: unknown;
};

export type CreateExportApiV1ExportsPostResponses = {
    /**
     * Generated workbook (XLSX, one tab per locale plus a hidden _meta tab) or XLIFF 1.2 document (one <file> per locale).
     */
    200: unknown;
};

export type PostPreviewApiV1ImportsPreviewPostData = {
    body: BodyPostPreviewApiV1ImportsPreviewPost;
    path?: never;
    query?: never;
    url: '/api/v1/imports/preview';
};

export type PostPreviewApiV1ImportsPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPreviewApiV1ImportsPreviewPostError = PostPreviewApiV1ImportsPreviewPostErrors[keyof PostPreviewApiV1ImportsPreviewPostErrors];

export type PostPreviewApiV1ImportsPreviewPostResponses = {
    /**
     * Successful Response
     */
    201: ImportPreviewResponse;
};

export type PostPreviewApiV1ImportsPreviewPostResponse = PostPreviewApiV1ImportsPreviewPostResponses[keyof PostPreviewApiV1ImportsPreviewPostResponses];

export type PostCommitApiV1ImportsJobIdCommitPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: {
        /**
         * Force Overwrite
         */
        force_overwrite?: boolean;
    };
    url: '/api/v1/imports/{job_id}/commit';
};

export type PostCommitApiV1ImportsJobIdCommitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostCommitApiV1ImportsJobIdCommitPostError = PostCommitApiV1ImportsJobIdCommitPostErrors[keyof PostCommitApiV1ImportsJobIdCommitPostErrors];

export type PostCommitApiV1ImportsJobIdCommitPostResponses = {
    /**
     * Successful Response
     */
    200: ImportCommitResponse;
};

export type PostCommitApiV1ImportsJobIdCommitPostResponse = PostCommitApiV1ImportsJobIdCommitPostResponses[keyof PostCommitApiV1ImportsJobIdCommitPostResponses];

export type PostRollbackApiV1ImportsJobIdRollbackPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{job_id}/rollback';
};

export type PostRollbackApiV1ImportsJobIdRollbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRollbackApiV1ImportsJobIdRollbackPostError = PostRollbackApiV1ImportsJobIdRollbackPostErrors[keyof PostRollbackApiV1ImportsJobIdRollbackPostErrors];

export type PostRollbackApiV1ImportsJobIdRollbackPostResponses = {
    /**
     * Successful Response
     */
    200: ImportRollbackResponse;
};

export type PostRollbackApiV1ImportsJobIdRollbackPostResponse = PostRollbackApiV1ImportsJobIdRollbackPostResponses[keyof PostRollbackApiV1ImportsJobIdRollbackPostResponses];

export type ListKeysApiV1KeysGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Repository Id
         */
        repository_id?: string | null;
        /**
         * Locale
         */
        locale?: string | null;
        /**
         * Status
         */
        status?: TranslationStatus | null;
        /**
         * Component
         */
        component?: string | null;
        /**
         * Id
         */
        id?: Array<string> | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/keys';
};

export type ListKeysApiV1KeysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListKeysApiV1KeysGetError = ListKeysApiV1KeysGetErrors[keyof ListKeysApiV1KeysGetErrors];

export type ListKeysApiV1KeysGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseKeyRead;
};

export type ListKeysApiV1KeysGetResponse = ListKeysApiV1KeysGetResponses[keyof ListKeysApiV1KeysGetResponses];

export type GetKeyApiV1KeysKeyIdGetData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/keys/{key_id}';
};

export type GetKeyApiV1KeysKeyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKeyApiV1KeysKeyIdGetError = GetKeyApiV1KeysKeyIdGetErrors[keyof GetKeyApiV1KeysKeyIdGetErrors];

export type GetKeyApiV1KeysKeyIdGetResponses = {
    /**
     * Successful Response
     */
    200: KeyDetail;
};

export type GetKeyApiV1KeysKeyIdGetResponse = GetKeyApiV1KeysKeyIdGetResponses[keyof GetKeyApiV1KeysKeyIdGetResponses];

export type UpdateKeyApiV1KeysKeyIdPatchData = {
    body: KeyUpdate;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/keys/{key_id}';
};

export type UpdateKeyApiV1KeysKeyIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateKeyApiV1KeysKeyIdPatchError = UpdateKeyApiV1KeysKeyIdPatchErrors[keyof UpdateKeyApiV1KeysKeyIdPatchErrors];

export type UpdateKeyApiV1KeysKeyIdPatchResponses = {
    /**
     * Successful Response
     */
    200: KeyRead;
};

export type UpdateKeyApiV1KeysKeyIdPatchResponse = UpdateKeyApiV1KeysKeyIdPatchResponses[keyof UpdateKeyApiV1KeysKeyIdPatchResponses];

export type ListScreenshotsApiV1KeysKeyIdScreenshotsGetData = {
    body?: never;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/keys/{key_id}/screenshots';
};

export type ListScreenshotsApiV1KeysKeyIdScreenshotsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListScreenshotsApiV1KeysKeyIdScreenshotsGetError = ListScreenshotsApiV1KeysKeyIdScreenshotsGetErrors[keyof ListScreenshotsApiV1KeysKeyIdScreenshotsGetErrors];

export type ListScreenshotsApiV1KeysKeyIdScreenshotsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseScreenshotRead;
};

export type ListScreenshotsApiV1KeysKeyIdScreenshotsGetResponse = ListScreenshotsApiV1KeysKeyIdScreenshotsGetResponses[keyof ListScreenshotsApiV1KeysKeyIdScreenshotsGetResponses];

export type UploadScreenshotApiV1KeysKeyIdScreenshotsPostData = {
    body: BodyUploadScreenshotApiV1KeysKeyIdScreenshotsPost;
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/keys/{key_id}/screenshots';
};

export type UploadScreenshotApiV1KeysKeyIdScreenshotsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadScreenshotApiV1KeysKeyIdScreenshotsPostError = UploadScreenshotApiV1KeysKeyIdScreenshotsPostErrors[keyof UploadScreenshotApiV1KeysKeyIdScreenshotsPostErrors];

export type UploadScreenshotApiV1KeysKeyIdScreenshotsPostResponses = {
    /**
     * Successful Response
     */
    201: ScreenshotRead;
};

export type UploadScreenshotApiV1KeysKeyIdScreenshotsPostResponse = UploadScreenshotApiV1KeysKeyIdScreenshotsPostResponses[keyof UploadScreenshotApiV1KeysKeyIdScreenshotsPostResponses];

export type ListOrgsApiV1OrganizationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type ListOrgsApiV1OrganizationsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseOrgRead;
};

export type ListOrgsApiV1OrganizationsGetResponse = ListOrgsApiV1OrganizationsGetResponses[keyof ListOrgsApiV1OrganizationsGetResponses];

export type CreateOrgApiV1OrganizationsPostData = {
    body: OrgCreate;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type CreateOrgApiV1OrganizationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrgApiV1OrganizationsPostError = CreateOrgApiV1OrganizationsPostErrors[keyof CreateOrgApiV1OrganizationsPostErrors];

export type CreateOrgApiV1OrganizationsPostResponses = {
    /**
     * Successful Response
     */
    201: OrgRead;
};

export type CreateOrgApiV1OrganizationsPostResponse = CreateOrgApiV1OrganizationsPostResponses[keyof CreateOrgApiV1OrganizationsPostResponses];

export type DeleteOrgApiV1OrganizationsOrgIdDeleteData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}';
};

export type DeleteOrgApiV1OrganizationsOrgIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOrgApiV1OrganizationsOrgIdDeleteError = DeleteOrgApiV1OrganizationsOrgIdDeleteErrors[keyof DeleteOrgApiV1OrganizationsOrgIdDeleteErrors];

export type DeleteOrgApiV1OrganizationsOrgIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteOrgApiV1OrganizationsOrgIdDeleteResponse = DeleteOrgApiV1OrganizationsOrgIdDeleteResponses[keyof DeleteOrgApiV1OrganizationsOrgIdDeleteResponses];

export type GetOrgApiV1OrganizationsOrgIdGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}';
};

export type GetOrgApiV1OrganizationsOrgIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrgApiV1OrganizationsOrgIdGetError = GetOrgApiV1OrganizationsOrgIdGetErrors[keyof GetOrgApiV1OrganizationsOrgIdGetErrors];

export type GetOrgApiV1OrganizationsOrgIdGetResponses = {
    /**
     * Successful Response
     */
    200: OrgRead;
};

export type GetOrgApiV1OrganizationsOrgIdGetResponse = GetOrgApiV1OrganizationsOrgIdGetResponses[keyof GetOrgApiV1OrganizationsOrgIdGetResponses];

export type UpdateOrgApiV1OrganizationsOrgIdPatchData = {
    body: OrgUpdate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}';
};

export type UpdateOrgApiV1OrganizationsOrgIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrgApiV1OrganizationsOrgIdPatchError = UpdateOrgApiV1OrganizationsOrgIdPatchErrors[keyof UpdateOrgApiV1OrganizationsOrgIdPatchErrors];

export type UpdateOrgApiV1OrganizationsOrgIdPatchResponses = {
    /**
     * Successful Response
     */
    200: OrgRead;
};

export type UpdateOrgApiV1OrganizationsOrgIdPatchResponse = UpdateOrgApiV1OrganizationsOrgIdPatchResponses[keyof UpdateOrgApiV1OrganizationsOrgIdPatchResponses];

export type ListProjectsApiV1OrganizationsOrgIdProjectsGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/projects';
};

export type ListProjectsApiV1OrganizationsOrgIdProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsApiV1OrganizationsOrgIdProjectsGetError = ListProjectsApiV1OrganizationsOrgIdProjectsGetErrors[keyof ListProjectsApiV1OrganizationsOrgIdProjectsGetErrors];

export type ListProjectsApiV1OrganizationsOrgIdProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseProjectRead;
};

export type ListProjectsApiV1OrganizationsOrgIdProjectsGetResponse = ListProjectsApiV1OrganizationsOrgIdProjectsGetResponses[keyof ListProjectsApiV1OrganizationsOrgIdProjectsGetResponses];

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostData = {
    body: ProjectCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/projects';
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostError = CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors[keyof CreateProjectApiV1OrganizationsOrgIdProjectsPostErrors];

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectApiV1OrganizationsOrgIdProjectsPostResponse = CreateProjectApiV1OrganizationsOrgIdProjectsPostResponses[keyof CreateProjectApiV1OrganizationsOrgIdProjectsPostResponses];

export type ListUsersApiV1OrganizationsOrgIdUsersGetData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/users';
};

export type ListUsersApiV1OrganizationsOrgIdUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiV1OrganizationsOrgIdUsersGetError = ListUsersApiV1OrganizationsOrgIdUsersGetErrors[keyof ListUsersApiV1OrganizationsOrgIdUsersGetErrors];

export type ListUsersApiV1OrganizationsOrgIdUsersGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseUserRead;
};

export type ListUsersApiV1OrganizationsOrgIdUsersGetResponse = ListUsersApiV1OrganizationsOrgIdUsersGetResponses[keyof ListUsersApiV1OrganizationsOrgIdUsersGetResponses];

export type CreateUserApiV1OrganizationsOrgIdUsersPostData = {
    body: UserCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/users';
};

export type CreateUserApiV1OrganizationsOrgIdUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1OrganizationsOrgIdUsersPostError = CreateUserApiV1OrganizationsOrgIdUsersPostErrors[keyof CreateUserApiV1OrganizationsOrgIdUsersPostErrors];

export type CreateUserApiV1OrganizationsOrgIdUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserApiV1OrganizationsOrgIdUsersPostResponse = CreateUserApiV1OrganizationsOrgIdUsersPostResponses[keyof CreateUserApiV1OrganizationsOrgIdUsersPostResponses];

export type GetLocaleApiV1OtaProjectSlugLocaleJsonGetData = {
    body?: never;
    path: {
        /**
         * Project Slug
         */
        project_slug: string;
        /**
         * Locale
         */
        locale: string;
    };
    query?: {
        /**
         * Platform
         */
        platform?: 'ios' | null;
    };
    url: '/api/v1/ota/{project_slug}/{locale}.json';
};

export type GetLocaleApiV1OtaProjectSlugLocaleJsonGetErrors = {
    /**
     * Project slug unknown or no published translations in that locale.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLocaleApiV1OtaProjectSlugLocaleJsonGetError = GetLocaleApiV1OtaProjectSlugLocaleJsonGetErrors[keyof GetLocaleApiV1OtaProjectSlugLocaleJsonGetErrors];

export type GetLocaleApiV1OtaProjectSlugLocaleJsonGetResponses = {
    /**
     * Locale payload returned (or 304 with no body if ETag matches).
     */
    200: unknown;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteError = DeleteProjectApiV1ProjectsProjectIdDeleteErrors[keyof DeleteProjectApiV1ProjectsProjectIdDeleteErrors];

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponse = DeleteProjectApiV1ProjectsProjectIdDeleteResponses[keyof DeleteProjectApiV1ProjectsProjectIdDeleteResponses];

export type GetProjectApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1ProjectsProjectIdGetError = GetProjectApiV1ProjectsProjectIdGetErrors[keyof GetProjectApiV1ProjectsProjectIdGetErrors];

export type GetProjectApiV1ProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type GetProjectApiV1ProjectsProjectIdGetResponse = GetProjectApiV1ProjectsProjectIdGetResponses[keyof GetProjectApiV1ProjectsProjectIdGetResponses];

export type UpdateProjectApiV1ProjectsProjectIdPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectApiV1ProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchError = UpdateProjectApiV1ProjectsProjectIdPatchErrors[keyof UpdateProjectApiV1ProjectsProjectIdPatchErrors];

export type UpdateProjectApiV1ProjectsProjectIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchResponse = UpdateProjectApiV1ProjectsProjectIdPatchResponses[keyof UpdateProjectApiV1ProjectsProjectIdPatchResponses];

export type ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/glossary';
};

export type ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetError = ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetErrors[keyof ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetErrors];

export type ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseGlossaryTermRead;
};

export type ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetResponse = ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetResponses[keyof ListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetResponses];

export type CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostData = {
    body: GlossaryTermCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/glossary';
};

export type CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostError = CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostErrors[keyof CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostErrors];

export type CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostResponses = {
    /**
     * Successful Response
     */
    201: GlossaryTermRead;
};

export type CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostResponse = CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostResponses[keyof CreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostResponses];

export type DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Term Id
         */
        term_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/glossary/{term_id}';
};

export type DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteError = DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteErrors[keyof DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteErrors];

export type DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteResponse = DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteResponses[keyof DeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteResponses];

export type GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Term Id
         */
        term_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/glossary/{term_id}';
};

export type GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetError = GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetErrors[keyof GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetErrors];

export type GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetResponses = {
    /**
     * Successful Response
     */
    200: GlossaryTermRead;
};

export type GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetResponse = GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetResponses[keyof GetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetResponses];

export type UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchData = {
    body: GlossaryTermUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Term Id
         */
        term_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/glossary/{term_id}';
};

export type UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchError = UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchErrors[keyof UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchErrors];

export type UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GlossaryTermRead;
};

export type UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchResponse = UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchResponses[keyof UpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchResponses];

export type ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/locale-configs';
};

export type ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetError = ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetErrors[keyof ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetErrors];

export type ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseLocaleConfigRead;
};

export type ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetResponse = ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetResponses[keyof ListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetResponses];

export type CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostData = {
    body: LocaleConfigCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Fan Out
         *
         * Activate the locale: fan out draft Translation rows for every active key in the project and flip is_activated=true. Idempotent — re-running inserts zero rows for keys that already have a translation for this locale. Without fan_out, the endpoint only creates/finds the locale_config row (state 1: 'registered').
         */
        fan_out?: boolean;
    };
    url: '/api/v1/projects/{project_id}/locale-configs';
};

export type CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostError = CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostErrors[keyof CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostErrors];

export type CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostResponses = {
    /**
     * Successful Response
     */
    200: LocaleConfigActivationResult;
};

export type CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostResponse = CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostResponses[keyof CreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostResponses];

export type DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/locale-configs/{config_id}';
};

export type DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteError = DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteErrors[keyof DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteErrors];

export type DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteResponse = DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteResponses[keyof DeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteResponses];

export type GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/locale-configs/{config_id}';
};

export type GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetError = GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetErrors[keyof GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetErrors];

export type GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetResponses = {
    /**
     * Successful Response
     */
    200: LocaleConfigRead;
};

export type GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetResponse = GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetResponses[keyof GetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetResponses];

export type UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchData = {
    body: LocaleConfigUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/locale-configs/{config_id}';
};

export type UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchError = UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchErrors[keyof UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchErrors];

export type UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchResponses = {
    /**
     * Successful Response
     */
    200: LocaleConfigRead;
};

export type UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchResponse = UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchResponses[keyof UpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchResponses];

export type ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/repositories';
};

export type ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetError = ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetErrors[keyof ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetErrors];

export type ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseRepositoryRead;
};

export type ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetResponse = ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetResponses[keyof ListRepositoriesApiV1ProjectsProjectIdRepositoriesGetResponses];

export type CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostData = {
    body: RepositoryCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/repositories';
};

export type CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostError = CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostErrors[keyof CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostErrors];

export type CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostResponses = {
    /**
     * Successful Response
     */
    201: RepositoryRead;
};

export type CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostResponse = CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostResponses[keyof CreateRepositoryApiV1ProjectsProjectIdRepositoriesPostResponses];

export type DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/repositories/{repo_id}';
};

export type DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteError = DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteErrors[keyof DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteErrors];

export type DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteResponse = DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteResponses[keyof DeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteResponses];

export type GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/repositories/{repo_id}';
};

export type GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetError = GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetErrors[keyof GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetErrors];

export type GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetResponses = {
    /**
     * Successful Response
     */
    200: RepositoryRead;
};

export type GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetResponse = GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetResponses[keyof GetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetResponses];

export type UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchData = {
    body: RepositoryUpdate;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/repositories/{repo_id}';
};

export type UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchError = UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchErrors[keyof UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchErrors];

export type UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RepositoryRead;
};

export type UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchResponse = UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchResponses[keyof UpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchResponses];

export type TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Locale
         *
         * Restrict to batches in this BCP-47 locale (e.g. 'de-DE'). Omitting fans out across every locale in the project.
         */
        locale?: string | null;
        /**
         * Status
         *
         * Batch status to enqueue. Default 'pending' covers the typical 'Translate N pending' flow. Pass 'mt_proposed' to retry batches whose primary MT call failed and need re-running.
         */
        status?: string;
    };
    url: '/api/v1/projects/{project_id}/trigger-mt';
};

export type TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostError = TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostErrors[keyof TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostErrors];

export type TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostResponses = {
    /**
     * Successful Response
     */
    200: BulkTriggerResult;
};

export type TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostResponse = TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostResponses[keyof TriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostResponses];

export type TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Locale
         *
         * Restrict the PR to approved translations for this BCP-47 locale. Omitting publishes every locale's approved set, which matches the pre-docs/15 behavior (CLI / scheduler callers).
         */
        locale?: string | null;
    };
    url: '/api/v1/publications/repositories/{repo_id}/publish';
};

export type TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostError = TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostErrors[keyof TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostErrors];

export type TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostResponses = {
    /**
     * Successful Response
     */
    200: PublishResult;
};

export type TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostResponse = TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostResponses[keyof TriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostResponses];

export type PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Locale
         *
         * Restrict the transition to this BCP-47 locale. Omitting publishes every locale's approved set for the repository.
         */
        locale?: string | null;
    };
    url: '/api/v1/publications/repositories/{repo_id}/publish-to-ota';
};

export type PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostError = PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostErrors[keyof PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostErrors];

export type PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostResponses = {
    /**
     * Successful Response
     */
    200: PublishToOtaResult;
};

export type PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostResponse = PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostResponses[keyof PublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostResponses];

export type ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/component-contexts';
};

export type ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetError = ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetErrors[keyof ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetErrors];

export type ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseComponentContextRead;
};

export type ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetResponse = ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetResponses[keyof ListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetResponses];

export type CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostData = {
    body: ComponentContextCreate;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/component-contexts';
};

export type CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostError = CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostErrors[keyof CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostErrors];

export type CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostResponses = {
    /**
     * Successful Response
     */
    201: ComponentContextRead;
};

export type CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostResponse = CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostResponses[keyof CreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostResponses];

export type DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
        /**
         * Ctx Id
         */
        ctx_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/component-contexts/{ctx_id}';
};

export type DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteError = DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteErrors[keyof DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteErrors];

export type DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteResponse = DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteResponses[keyof DeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteResponses];

export type GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
        /**
         * Ctx Id
         */
        ctx_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/component-contexts/{ctx_id}';
};

export type GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetError = GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetErrors[keyof GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetErrors];

export type GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetResponses = {
    /**
     * Successful Response
     */
    200: ComponentContextRead;
};

export type GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetResponse = GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetResponses[keyof GetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetResponses];

export type UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchData = {
    body: ComponentContextUpdate;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
        /**
         * Ctx Id
         */
        ctx_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/component-contexts/{ctx_id}';
};

export type UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchError = UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchErrors[keyof UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchErrors];

export type UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ComponentContextRead;
};

export type UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchResponse = UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchResponses[keyof UpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchResponses];

export type IngestRepositoryApiV1RepositoriesRepoIdIngestPostData = {
    body: IngestRequest;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/ingest';
};

export type IngestRepositoryApiV1RepositoriesRepoIdIngestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestRepositoryApiV1RepositoriesRepoIdIngestPostError = IngestRepositoryApiV1RepositoriesRepoIdIngestPostErrors[keyof IngestRepositoryApiV1RepositoriesRepoIdIngestPostErrors];

export type IngestRepositoryApiV1RepositoriesRepoIdIngestPostResponses = {
    /**
     * Successful Response
     */
    200: IngestResult;
};

export type IngestRepositoryApiV1RepositoriesRepoIdIngestPostResponse = IngestRepositoryApiV1RepositoriesRepoIdIngestPostResponses[keyof IngestRepositoryApiV1RepositoriesRepoIdIngestPostResponses];

export type DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteData = {
    body?: never;
    path: {
        /**
         * Screenshot Id
         */
        screenshot_id: string;
    };
    query?: never;
    url: '/api/v1/screenshots/{screenshot_id}';
};

export type DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteError = DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteErrors[keyof DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteErrors];

export type DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteResponse = DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteResponses[keyof DeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteResponses];

export type GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetData = {
    body?: never;
    path: {
        /**
         * Screenshot Id
         */
        screenshot_id: string;
    };
    query?: never;
    url: '/api/v1/screenshots/{screenshot_id}/image';
};

export type GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetError = GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetErrors[keyof GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetErrors];

export type GetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTranslationsApiV1TranslationsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project Id
         */
        project_id: string;
        /**
         * Locale
         */
        locale?: string | null;
        /**
         * Status
         */
        status?: TranslationStatus | null;
        /**
         * Key Id
         */
        key_id?: string | null;
        /**
         * Batch Id
         */
        batch_id?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/translations';
};

export type ListTranslationsApiV1TranslationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTranslationsApiV1TranslationsGetError = ListTranslationsApiV1TranslationsGetErrors[keyof ListTranslationsApiV1TranslationsGetErrors];

export type ListTranslationsApiV1TranslationsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseTranslationRead;
};

export type ListTranslationsApiV1TranslationsGetResponse = ListTranslationsApiV1TranslationsGetResponses[keyof ListTranslationsApiV1TranslationsGetResponses];

export type GetTranslationApiV1TranslationsTranslationIdGetData = {
    body?: never;
    path: {
        /**
         * Translation Id
         */
        translation_id: string;
    };
    query?: never;
    url: '/api/v1/translations/{translation_id}';
};

export type GetTranslationApiV1TranslationsTranslationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTranslationApiV1TranslationsTranslationIdGetError = GetTranslationApiV1TranslationsTranslationIdGetErrors[keyof GetTranslationApiV1TranslationsTranslationIdGetErrors];

export type GetTranslationApiV1TranslationsTranslationIdGetResponses = {
    /**
     * Successful Response
     */
    200: TranslationRead;
};

export type GetTranslationApiV1TranslationsTranslationIdGetResponse = GetTranslationApiV1TranslationsTranslationIdGetResponses[keyof GetTranslationApiV1TranslationsTranslationIdGetResponses];

export type UpdateTranslationApiV1TranslationsTranslationIdPatchData = {
    body: TranslationUpdate;
    path: {
        /**
         * Translation Id
         */
        translation_id: string;
    };
    query?: never;
    url: '/api/v1/translations/{translation_id}';
};

export type UpdateTranslationApiV1TranslationsTranslationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTranslationApiV1TranslationsTranslationIdPatchError = UpdateTranslationApiV1TranslationsTranslationIdPatchErrors[keyof UpdateTranslationApiV1TranslationsTranslationIdPatchErrors];

export type UpdateTranslationApiV1TranslationsTranslationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TranslationRead;
};

export type UpdateTranslationApiV1TranslationsTranslationIdPatchResponse = UpdateTranslationApiV1TranslationsTranslationIdPatchResponses[keyof UpdateTranslationApiV1TranslationsTranslationIdPatchResponses];

export type GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetData = {
    body?: never;
    path: {
        /**
         * Translation Id
         */
        translation_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/translations/{translation_id}/history';
};

export type GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetError = GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetErrors[keyof GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetErrors];

export type GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseTranslationHistoryRead;
};

export type GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetResponse = GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetResponses[keyof GetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetResponses];

export type ReceiveContentfulWebhookApiV1WebhooksContentfulPostData = {
    body?: never;
    headers?: {
        /**
         * X-Contentful-Webhook-Secret
         */
        'x-contentful-webhook-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/contentful';
};

export type ReceiveContentfulWebhookApiV1WebhooksContentfulPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveContentfulWebhookApiV1WebhooksContentfulPostError = ReceiveContentfulWebhookApiV1WebhooksContentfulPostErrors[keyof ReceiveContentfulWebhookApiV1WebhooksContentfulPostErrors];

export type ReceiveContentfulWebhookApiV1WebhooksContentfulPostResponses = {
    /**
     * Successful Response
     */
    200: WebhookAck;
};

export type ReceiveContentfulWebhookApiV1WebhooksContentfulPostResponse = ReceiveContentfulWebhookApiV1WebhooksContentfulPostResponses[keyof ReceiveContentfulWebhookApiV1WebhooksContentfulPostResponses];

export type ReceiveGithubWebhookApiV1WebhooksGithubPostData = {
    body?: never;
    headers?: {
        /**
         * X-Hub-Signature-256
         */
        'x-hub-signature-256'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/github';
};

export type ReceiveGithubWebhookApiV1WebhooksGithubPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveGithubWebhookApiV1WebhooksGithubPostError = ReceiveGithubWebhookApiV1WebhooksGithubPostErrors[keyof ReceiveGithubWebhookApiV1WebhooksGithubPostErrors];

export type ReceiveGithubWebhookApiV1WebhooksGithubPostResponses = {
    /**
     * Successful Response
     */
    200: WebhookAck;
};

export type ReceiveGithubWebhookApiV1WebhooksGithubPostResponse = ReceiveGithubWebhookApiV1WebhooksGithubPostResponses[keyof ReceiveGithubWebhookApiV1WebhooksGithubPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type HealthSchedulerHealthSchedulerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/scheduler';
};

export type HealthSchedulerHealthSchedulerGetResponses = {
    /**
     * Response Health Scheduler Health Scheduler Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthSchedulerHealthSchedulerGetResponse = HealthSchedulerHealthSchedulerGetResponses[keyof HealthSchedulerHealthSchedulerGetResponses];
