// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ApiKeyCreate
 *
 * Payload for `POST /api-keys`.
 *
 * Note: the new key always inherits the calling key's organization. The
 * callable does not accept an `org_id` field — any such field in the body
 * is ignored, not honored, to prevent cross-tenant privilege escalation.
 */
export const zApiKeyCreate = z.object({
    name: z.string()
});

/**
 * ApiKeyCreated
 *
 * Returned only once at creation time — includes the raw key.
 */
export const zApiKeyCreated = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid(),
    is_active: z.boolean(),
    is_org_admin: z.boolean(),
    last_used_at: z.iso.datetime().nullable(),
    name: z.string(),
    organization_id: z.uuid(),
    raw_key: z.string()
});

/**
 * ApiKeyRead
 */
export const zApiKeyRead = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid(),
    is_active: z.boolean(),
    is_org_admin: z.boolean(),
    last_used_at: z.iso.datetime().nullable(),
    name: z.string(),
    organization_id: z.uuid()
});

/**
 * AppSettingsRead
 */
export const zAppSettingsRead = z.object({
    evaluate_temperature: z.number(),
    fallback_chain: z.array(z.string()),
    has_anthropic_key: z.boolean(),
    has_deepl_key: z.boolean(),
    has_openai_key: z.boolean(),
    has_openrouter_key: z.boolean(),
    ollama_host: z.string().nullable(),
    openrouter_model: z.string(),
    primary_provider: z.string(),
    translate_temperature: z.number()
});

/**
 * AppSettingsUpdate
 *
 * Partial-update body — every field is optional.
 *
 * Note the distinction between "field omitted" (no-op) and "field set to
 * empty string" (clear the encrypted column). Use ``exclude_unset=True``
 * on the server to make that split, not ``exclude_none``.
 */
export const zAppSettingsUpdate = z.object({
    anthropic_api_key: z.string().nullish(),
    deepl_api_key: z.string().nullish(),
    evaluate_temperature: z.number().gte(0).lte(2).nullish(),
    fallback_chain: z.array(z.string()).nullish(),
    ollama_host: z.string().nullish(),
    openai_api_key: z.string().nullish(),
    openrouter_api_key: z.string().nullish(),
    openrouter_model: z.string().min(1).nullish(),
    primary_provider: z.string().nullish(),
    translate_temperature: z.number().gte(0).lte(2).nullish()
});

/**
 * BatchApproveResult
 */
export const zBatchApproveResult = z.object({
    approved: z.int(),
    batch_id: z.string(),
    skipped: z.int()
});

/**
 * BatchRead
 */
export const zBatchRead = z.object({
    component: z.string(),
    created_at: z.iso.datetime(),
    id: z.uuid(),
    locale: z.string(),
    mt_model: z.string().nullable(),
    mt_prompt_version: z.string().nullable(),
    project_id: z.uuid(),
    ran_at: z.iso.datetime().nullable(),
    repository_id: z.uuid(),
    screen: z.string().nullable(),
    status: z.string()
});

/**
 * BatchRejectResult
 */
export const zBatchRejectResult = z.object({
    batch_id: z.string(),
    rejected: z.int(),
    skipped: z.int()
});

/**
 * BatchStats
 */
export const zBatchStats = z.object({
    approved: z.int(),
    needs_review: z.int(),
    total_keys: z.int(),
    translated: z.int()
});

/**
 * BatchDetail
 *
 * GET /batches/{id} — the BatchRead fields plus a computed stats block.
 */
export const zBatchDetail = z.object({
    component: z.string(),
    created_at: z.iso.datetime(),
    id: z.uuid(),
    locale: z.string(),
    mt_model: z.string().nullable(),
    mt_prompt_version: z.string().nullable(),
    project_id: z.uuid(),
    ran_at: z.iso.datetime().nullable(),
    repository_id: z.uuid(),
    screen: z.string().nullable(),
    stats: zBatchStats,
    status: z.string()
});

/**
 * BatchStatus
 */
export const zBatchStatus = z.enum([
    'pending',
    'mt_running',
    'mt_complete',
    'needs_review',
    'approved',
    'published'
]);

/**
 * BatchTrigger
 */
export const zBatchTrigger = z.object({
    provider: z.string().optional().default('anthropic')
});

/**
 * BatchTriggerResult
 */
export const zBatchTriggerResult = z.object({
    batch_id: z.string(),
    provider: z.string(),
    status: z.string()
});

/**
 * Body_post_preview_api_v1_imports_preview_post
 */
export const zBodyPostPreviewApiV1ImportsPreviewPost = z.object({
    file: z.string(),
    format: z.enum(['xlsx', 'xliff']).nullish(),
    project_id: z.uuid()
});

/**
 * Body_upload_screenshot_api_v1_keys__key_id__screenshots_post
 */
export const zBodyUploadScreenshotApiV1KeysKeyIdScreenshotsPost = z.object({
    caption: z.string().nullish(),
    file: z.string()
});

/**
 * BulkTriggerResult
 */
export const zBulkTriggerResult = z.object({
    queued: z.int(),
    skipped: z.int()
});

/**
 * ComponentContextCreate
 */
export const zComponentContextCreate = z.object({
    component: z.string(),
    default_max_length: z.int().nullish(),
    default_risk_class: z.string().optional().default('standard'),
    description: z.string(),
    notes: z.string().nullish(),
    screen: z.string().nullish()
});

/**
 * ComponentContextRead
 */
export const zComponentContextRead = z.object({
    component: z.string(),
    created_at: z.iso.datetime(),
    default_max_length: z.int().nullable(),
    default_risk_class: z.string(),
    description: z.string(),
    id: z.uuid(),
    notes: z.string().nullable(),
    repository_id: z.uuid(),
    screen: z.string().nullable()
});

/**
 * ComponentContextUpdate
 */
export const zComponentContextUpdate = z.object({
    component: z.string().nullish(),
    default_max_length: z.int().nullish(),
    default_risk_class: z.string().nullish(),
    description: z.string().nullish(),
    notes: z.string().nullish(),
    screen: z.string().nullish()
});

/**
 * CostByModel
 *
 * One row of the cost-by-model breakdown (mirrors the CLAUDE.md cost query).
 */
export const zCostByModel = z.object({
    cost_usd: z.number(),
    input_tokens: z.int(),
    model: z.string(),
    output_tokens: z.int(),
    runs: z.int()
});

/**
 * AnalyticsSummary
 *
 * Aggregate metrics for one project over a trailing window.
 *
 * Windowing differs per section by design:
 * - cost / throughput: ``mt_runs.ran_at`` >= cutoff
 * - edit rate:         ``translations.reviewed_at`` >= cutoff
 * - QA averages:       ``translations.mt_run_at`` >= cutoff
 * - ``status_counts``: NOT windowed — it's the project's current queue
 * composition (a live snapshot), so a time filter would be misleading.
 */
export const zAnalyticsSummary = z.object({
    accept_count: z.int(),
    avg_back_translation_similarity: z.number().nullable(),
    avg_latency_ms: z.number().nullable(),
    avg_qa_accuracy: z.number().nullable(),
    avg_qa_consistency: z.number().nullable(),
    avg_qa_naturalness: z.number().nullable(),
    cost_by_model: z.array(zCostByModel),
    edit_count: z.int(),
    edit_rate: z.number().nullable(),
    needs_more_context_count: z.int(),
    reject_count: z.int(),
    reviewed_count: z.int(),
    status_counts: z.record(z.string(), z.int()),
    total_cost_usd: z.number(),
    total_input_tokens: z.int(),
    total_output_tokens: z.int(),
    total_runs: z.int(),
    window_days: z.int()
});

/**
 * ExportCreate
 */
export const zExportCreate = z.object({
    format: z.enum(['xlsx', 'xliff']).optional().default('xlsx'),
    locales: z.array(z.string()).min(1),
    project_id: z.uuid(),
    sample_size: z.int().gte(1).lte(500).nullish(),
    status_filter: z.string().nullish()
});

/**
 * GlossaryTermCreate
 */
export const zGlossaryTermCreate = z.object({
    case_sensitive: z.boolean().optional().default(false),
    do_not_translate: z.boolean().optional().default(false),
    locale: z.string(),
    notes: z.string().nullish(),
    source_term: z.string(),
    target_term: z.string()
});

/**
 * GlossaryTermRead
 */
export const zGlossaryTermRead = z.object({
    case_sensitive: z.boolean(),
    created_at: z.iso.datetime(),
    created_by: z.uuid().nullable(),
    do_not_translate: z.boolean(),
    id: z.uuid(),
    locale: z.string(),
    notes: z.string().nullable(),
    project_id: z.uuid(),
    source_term: z.string(),
    target_term: z.string()
});

/**
 * GlossaryTermUpdate
 */
export const zGlossaryTermUpdate = z.object({
    case_sensitive: z.boolean().nullish(),
    do_not_translate: z.boolean().nullish(),
    notes: z.string().nullish(),
    target_term: z.string().nullish()
});

/**
 * ImportCommitResponse
 */
export const zImportCommitResponse = z.object({
    applied_changes_count: z.int(),
    committed_at: z.string().nullable(),
    job_id: z.string(),
    rollback_expires_at: z.string().nullable(),
    skipped_count: z.int(),
    status: z.string()
});

/**
 * ImportConflicts
 *
 * Conflict breakdown — source/translation changed since export.
 */
export const zImportConflicts = z.object({
    details: z.array(z.record(z.string(), z.unknown())),
    source_changed: z.int(),
    translation_modified_externally: z.int()
});

/**
 * ImportCounts
 *
 * Per-action row counts in a dry-run summary (``_summary_to_dict`` counts).
 */
export const zImportCounts = z.object({
    approve: z.int(),
    edit: z.int(),
    needs_more_context: z.int(),
    reject: z.int(),
    skip: z.int(),
    unknown: z.int()
});

/**
 * ImportDryRunSummary
 *
 * The ``dry_run_summary`` payload returned inside a preview response.
 *
 * Mirrors ``_summary_to_dict``. ``validation_errors`` / ``action_plan`` are
 * lists of per-row dicts (display-only on the client), kept loosely typed.
 */
export const zImportDryRunSummary = z.object({
    action_plan: z.array(z.record(z.string(), z.unknown())),
    conflicts: zImportConflicts,
    counts: zImportCounts,
    export_timestamp: z.string().nullable(),
    format: z.string().nullish(),
    locales: z.array(z.string()),
    project_id: z.string(),
    schema_version: z.string(),
    total_rows: z.int(),
    validation_error_count: z.int(),
    validation_errors: z.array(z.record(z.string(), z.unknown()))
});

/**
 * ImportPreviewResponse
 */
export const zImportPreviewResponse = z.object({
    job_id: z.string(),
    status: z.string(),
    summary: zImportDryRunSummary
});

/**
 * ImportRollbackResponse
 */
export const zImportRollbackResponse = z.object({
    job_id: z.string(),
    status: z.string()
});

/**
 * IngestRequest
 */
export const zIngestRequest = z.object({
    auto_translate: z.boolean().optional().default(true),
    content: z.string(),
    format: z.string(),
    on_conflict: z.string().optional().default('update_source'),
    path: z.string()
});

/**
 * IngestResult
 */
export const zIngestResult = z.object({
    batches: z.array(z.record(z.string(), z.unknown())),
    created: z.int(),
    format: z.string(),
    keys: z.array(z.record(z.string(), z.unknown())),
    parsed: z.int(),
    path: z.string(),
    repository_id: z.string(),
    unchanged: z.int(),
    updated: z.int()
});

/**
 * KeyRead
 */
export const zKeyRead = z.object({
    component: z.string().nullish(),
    context: z.string().nullish(),
    created_at: z.iso.datetime(),
    file_format: z.string().nullish(),
    has_structural_tags: z.boolean().optional().default(false),
    icu_shape: z.string().nullish(),
    id: z.uuid(),
    is_active: z.boolean(),
    key: z.string(),
    max_length: z.int().nullable(),
    placeholders: z.array(z.string()).optional().default([]),
    plural_format: z.string().nullable(),
    project_id: z.uuid(),
    repository_id: z.uuid(),
    risk_class: z.string(),
    screen: z.string().nullish(),
    source_text: z.string(),
    string_type: z.string().nullable()
});

/**
 * KeyUpdate
 */
export const zKeyUpdate = z.object({
    context: z.string().nullish(),
    is_active: z.boolean().nullish(),
    max_length: z.int().nullish(),
    risk_class: z.string().nullish(),
    source_text: z.string().nullish()
});

/**
 * ListResponse[ApiKeyRead]
 */
export const zListResponseApiKeyRead = z.object({
    items: z.array(zApiKeyRead),
    total: z.int().nullish()
});

/**
 * ListResponse[BatchRead]
 */
export const zListResponseBatchRead = z.object({
    items: z.array(zBatchRead),
    total: z.int().nullish()
});

/**
 * ListResponse[ComponentContextRead]
 */
export const zListResponseComponentContextRead = z.object({
    items: z.array(zComponentContextRead),
    total: z.int().nullish()
});

/**
 * ListResponse[GlossaryTermRead]
 */
export const zListResponseGlossaryTermRead = z.object({
    items: z.array(zGlossaryTermRead),
    total: z.int().nullish()
});

/**
 * ListResponse[KeyRead]
 */
export const zListResponseKeyRead = z.object({
    items: z.array(zKeyRead),
    total: z.int().nullish()
});

/**
 * LocaleConfigCreate
 */
export const zLocaleConfigCreate = z.object({
    formality: z.string().optional().default('formal'),
    is_bootstrapped: z.boolean().optional().default(false),
    locale: z.string(),
    notes: z.string().nullish(),
    register: z.string().nullish()
});

/**
 * LocaleConfigRead
 */
export const zLocaleConfigRead = z.object({
    bootstrap_state: z.record(z.string(), z.unknown()).nullish(),
    created_at: z.iso.datetime(),
    formality: z.string(),
    id: z.uuid(),
    is_activated: z.boolean(),
    is_bootstrapped: z.boolean(),
    locale: z.string(),
    notes: z.string().nullable(),
    project_id: z.uuid(),
    register: z.string().nullish()
});

/**
 * ListResponse[LocaleConfigRead]
 */
export const zListResponseLocaleConfigRead = z.object({
    items: z.array(zLocaleConfigRead),
    total: z.int().nullish()
});

/**
 * LocaleConfigActivationResult
 *
 * Response shape for `POST /locale-configs?fan_out=true`.
 *
 * Returned alongside the created/found `locale_config` row so the UI can
 * render an immediate success state ("Seeded 247 drafts · Bootstrap →").
 */
export const zLocaleConfigActivationResult = z.object({
    already_existed: z.boolean(),
    drafts_created: z.int(),
    locale_config: zLocaleConfigRead
});

/**
 * LocaleConfigUpdate
 */
export const zLocaleConfigUpdate = z.object({
    bootstrap_state: z.record(z.string(), z.unknown()).nullish(),
    formality: z.string().nullish(),
    is_activated: z.boolean().nullish(),
    is_bootstrapped: z.boolean().nullish(),
    notes: z.string().nullish(),
    register: z.string().nullish()
});

/**
 * MtRunRead
 *
 * One row from the `mt_runs` audit table.
 *
 * Powers the Phase 6 key-detail MT-run inspector. One row per LLM call —
 * primary attempt, retry, fallback. Full prompt + output text are
 * included so reviewers can dig into a specific translation's provenance.
 */
export const zMtRunRead = z.object({
    batch_id: z.uuid().nullable(),
    cost_usd: z.number().nullable(),
    id: z.uuid(),
    input_tokens: z.int().nullable(),
    latency_ms: z.int().nullable(),
    model: z.string(),
    output_text: z.string(),
    output_tokens: z.int().nullable(),
    prompt_text: z.string(),
    prompt_version: z.string(),
    ran_at: z.iso.datetime(),
    string_count: z.int().nullable(),
    validator_errors: z.record(z.string(), z.unknown()).nullable(),
    validators_passed: z.boolean().nullable()
});

/**
 * ListResponse[MtRunRead]
 */
export const zListResponseMtRunRead = z.object({
    items: z.array(zMtRunRead),
    total: z.int().nullish()
});

/**
 * OrgCreate
 */
export const zOrgCreate = z.object({
    admin_email: z.string().nullish(),
    admin_name: z.string().nullish(),
    name: z.string(),
    slug: z.string()
});

/**
 * OrgRead
 */
export const zOrgRead = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid(),
    name: z.string(),
    slug: z.string()
});

/**
 * ListResponse[OrgRead]
 */
export const zListResponseOrgRead = z.object({
    items: z.array(zOrgRead),
    total: z.int().nullish()
});

/**
 * OrgUpdate
 */
export const zOrgUpdate = z.object({
    name: z.string().nullish(),
    slug: z.string().nullish()
});

/**
 * ProjectCreate
 */
export const zProjectCreate = z.object({
    name: z.string(),
    slug: z.string(),
    source_locale: z.string().optional().default('en-US'),
    style_guide: z.string().nullish(),
    target_locales: z.array(z.string()).optional().default([])
});

/**
 * ProjectRead
 */
export const zProjectRead = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid(),
    name: z.string(),
    organization_id: z.uuid(),
    slug: z.string(),
    source_locale: z.string(),
    style_guide: z.string().nullable(),
    target_locales: z.array(z.string())
});

/**
 * ListResponse[ProjectRead]
 */
export const zListResponseProjectRead = z.object({
    items: z.array(zProjectRead),
    total: z.int().nullish()
});

/**
 * ProjectUpdate
 */
export const zProjectUpdate = z.object({
    name: z.string().nullish(),
    slug: z.string().nullish(),
    source_locale: z.string().nullish(),
    style_guide: z.string().nullish(),
    target_locales: z.array(z.string()).nullish()
});

/**
 * PublishResult
 *
 * POST /publications/repositories/{id}/publish.
 *
 * ``status`` is "ok" (PR opened) or "no_op" (nothing approved to publish);
 * ``pr_url`` is None on no_op. ``detail`` is only present on no_op, so it is
 * optional here.
 */
export const zPublishResult = z.object({
    detail: z.string().nullish(),
    locale: z.string().nullable(),
    pr_url: z.string().nullable(),
    status: z.string()
});

/**
 * PublishToOtaResult
 *
 * POST /publications/repositories/{id}/publish-to-ota.
 */
export const zPublishToOtaResult = z.object({
    locale: z.string().nullable(),
    published: z.int(),
    status: z.string()
});

/**
 * RepositoryCreate
 */
export const zRepositoryCreate = z.object({
    contentful_env: z.string().nullish().default('master'),
    contentful_space_id: z.string().nullish(),
    contentful_token: z.string().nullish(),
    contentful_webhook_secret: z.string().nullish(),
    context_notes: z.string().nullish(),
    default_branch: z.string().optional().default('main'),
    file_format: z.string(),
    github_installation_id: z.int().nullish(),
    github_path: z.string().nullish(),
    github_repo: z.string().nullish(),
    name: z.string(),
    platform: z.string(),
    plural_convention: z.string().optional().default('icu'),
    source_file: z.string().nullish(),
    webhook_secret: z.string().nullish()
});

/**
 * RepositoryRead
 *
 * Public read schema.
 *
 * Secret columns are NEVER returned by value. We expose three booleans
 * (`has_webhook_secret`, `has_contentful_token`, `has_contentful_webhook_secret`)
 * so clients can show "Secret configured" UI without ever receiving the
 * ciphertext or plaintext.
 */
export const zRepositoryRead = z.object({
    contentful_env: z.string().nullable(),
    contentful_space_id: z.string().nullable(),
    context_notes: z.string().nullable(),
    created_at: z.iso.datetime(),
    default_branch: z.string(),
    file_format: z.string(),
    github_installation_id: z.int().nullable(),
    github_path: z.string().nullable(),
    github_repo: z.string().nullable(),
    has_contentful_token: z.boolean().optional().default(false),
    has_contentful_webhook_secret: z.boolean().optional().default(false),
    has_webhook_secret: z.boolean().optional().default(false),
    id: z.uuid(),
    name: z.string(),
    platform: z.string(),
    plural_convention: z.string(),
    project_id: z.uuid(),
    source_file: z.string().nullable()
});

/**
 * ListResponse[RepositoryRead]
 */
export const zListResponseRepositoryRead = z.object({
    items: z.array(zRepositoryRead),
    total: z.int().nullish()
});

/**
 * RepositoryUpdate
 */
export const zRepositoryUpdate = z.object({
    contentful_env: z.string().nullish(),
    contentful_space_id: z.string().nullish(),
    contentful_token: z.string().nullish(),
    contentful_webhook_secret: z.string().nullish(),
    context_notes: z.string().nullish(),
    default_branch: z.string().nullish(),
    file_format: z.string().nullish(),
    github_installation_id: z.int().nullish(),
    github_path: z.string().nullish(),
    github_repo: z.string().nullish(),
    name: z.string().nullish(),
    platform: z.string().nullish(),
    plural_convention: z.string().nullish(),
    source_file: z.string().nullish(),
    webhook_secret: z.string().nullish()
});

/**
 * ScreenshotRead
 *
 * Wire-format Screenshot. Used by both upload (201) and list responses.
 */
export const zScreenshotRead = z.object({
    caption: z.string().nullish(),
    id: z.uuid(),
    key_id: z.uuid(),
    storage_url: z.string(),
    uploaded_at: z.iso.datetime()
});

/**
 * ListResponse[ScreenshotRead]
 */
export const zListResponseScreenshotRead = z.object({
    items: z.array(zScreenshotRead),
    total: z.int().nullish()
});

/**
 * TranslationHistoryRead
 *
 * One row from the `translation_history` audit log.
 *
 * Written by the Postgres `record_translation_history()` trigger on every
 * UPDATE of `translations` (see migration `0001` + `0006`). The actor
 * identity (`changed_by`, `change_source`) comes from session-level GUCs
 * set by `app.core.database.set_request_attribution`.
 */
export const zTranslationHistoryRead = z.object({
    change_note: z.string().nullable(),
    change_source: z.string().nullable(),
    changed_at: z.iso.datetime(),
    changed_by: z.uuid().nullable(),
    id: z.int(),
    new_status: z.string().nullable(),
    new_value: z.string().nullable(),
    prev_status: z.string().nullable(),
    prev_value: z.string().nullable(),
    translation_id: z.uuid()
});

/**
 * ListResponse[TranslationHistoryRead]
 */
export const zListResponseTranslationHistoryRead = z.object({
    items: z.array(zTranslationHistoryRead),
    total: z.int().nullish()
});

/**
 * TranslationRead
 */
export const zTranslationRead = z.object({
    back_translation: z.string().nullable(),
    back_translation_similarity: z.number().nullable(),
    batch_id: z.uuid().nullable(),
    id: z.uuid(),
    key_id: z.uuid(),
    locale: z.string(),
    mt_model: z.string().nullable(),
    mt_value: z.string().nullable(),
    qa_accuracy: z.int().nullable(),
    qa_consistency: z.int().nullable(),
    qa_issue: z.string().nullish(),
    qa_naturalness: z.int().nullable(),
    reviewed_at: z.iso.datetime().nullable(),
    reviewer_action: z.string().nullable(),
    reviewer_notes: z.string().nullish(),
    status: z.string(),
    updated_at: z.iso.datetime(),
    value: z.string().nullable()
});

/**
 * KeyDetail
 *
 * GET /keys/{id} — the KeyRead fields plus the key's translations.
 */
export const zKeyDetail = z.object({
    component: z.string().nullish(),
    context: z.string().nullish(),
    created_at: z.iso.datetime(),
    file_format: z.string().nullish(),
    has_structural_tags: z.boolean().optional().default(false),
    icu_shape: z.string().nullish(),
    id: z.uuid(),
    is_active: z.boolean(),
    key: z.string(),
    max_length: z.int().nullable(),
    placeholders: z.array(z.string()).optional().default([]),
    plural_format: z.string().nullable(),
    project_id: z.uuid(),
    repository_id: z.uuid(),
    risk_class: z.string(),
    screen: z.string().nullish(),
    source_text: z.string(),
    string_type: z.string().nullable(),
    translations: z.array(zTranslationRead)
});

/**
 * ListResponse[TranslationRead]
 */
export const zListResponseTranslationRead = z.object({
    items: z.array(zTranslationRead),
    total: z.int().nullish()
});

/**
 * TranslationStatus
 */
export const zTranslationStatus = z.enum([
    'draft',
    'mt_proposed',
    'needs_review',
    'needs_more_context',
    'approved',
    'rejected',
    'published'
]);

/**
 * TranslationUpdate
 */
export const zTranslationUpdate = z.object({
    reviewer_action: z.string().nullish(),
    reviewer_notes: z.string().nullish(),
    status: zTranslationStatus.nullish(),
    value: z.string().nullish()
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    assigned_locales: z.array(z.string()).optional().default([]),
    email: z.string(),
    name: z.string(),
    role: z.string().optional().default('developer')
});

/**
 * UserRead
 */
export const zUserRead = z.object({
    assigned_locales: z.array(z.string()),
    created_at: z.iso.datetime(),
    email: z.string(),
    id: z.uuid(),
    is_active: z.boolean(),
    name: z.string(),
    organization_id: z.uuid().nullable(),
    role: z.string()
});

/**
 * ListResponse[UserRead]
 */
export const zListResponseUserRead = z.object({
    items: z.array(zUserRead),
    total: z.int().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * WebhookAck
 */
export const zWebhookAck = z.object({
    reason: z.string().nullish(),
    status: z.string()
});

/**
 * Successful Response
 */
export const zListApiKeysApiV1ApiKeysGetResponse = zListResponseApiKeyRead;

export const zCreateApiKeyApiV1ApiKeysPostBody = zApiKeyCreate;

/**
 * Successful Response
 */
export const zCreateApiKeyApiV1ApiKeysPostResponse = zApiKeyCreated;

/**
 * Successful Response
 */
export const zGetCurrentApiKeyApiV1ApiKeysMeGetResponse = zApiKeyRead;

export const zRevokeApiKeyApiV1ApiKeysKeyIdDeletePath = z.object({
    key_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeApiKeyApiV1ApiKeysKeyIdDeleteResponse = z.void();

/**
 * Successful Response
 */
export const zGetAppSettingsApiV1AppSettingsGetResponse = zAppSettingsRead;

export const zUpdateAppSettingsApiV1AppSettingsPatchBody = zAppSettingsUpdate;

/**
 * Successful Response
 */
export const zUpdateAppSettingsApiV1AppSettingsPatchResponse = zAppSettingsRead;

export const zListBatchesApiV1BatchesGetQuery = z.object({
    project_id: z.uuid(),
    locale: z.string().nullish(),
    status: zBatchStatus.nullish(),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Successful Response
 */
export const zListBatchesApiV1BatchesGetResponse = zListResponseBatchRead;

export const zGetBatchApiV1BatchesBatchIdGetPath = z.object({
    batch_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetBatchApiV1BatchesBatchIdGetResponse = zBatchDetail;

export const zApproveBatchApiV1BatchesBatchIdApprovePostPath = z.object({
    batch_id: z.uuid()
});

/**
 * Successful Response
 */
export const zApproveBatchApiV1BatchesBatchIdApprovePostResponse = zBatchApproveResult;

export const zListMtRunsApiV1BatchesBatchIdMtRunsGetPath = z.object({
    batch_id: z.uuid()
});

export const zListMtRunsApiV1BatchesBatchIdMtRunsGetQuery = z.object({
    limit: z.int().gte(1).lte(500).optional().default(50)
});

/**
 * Successful Response
 */
export const zListMtRunsApiV1BatchesBatchIdMtRunsGetResponse = zListResponseMtRunRead;

export const zRejectBatchApiV1BatchesBatchIdRejectPostPath = z.object({
    batch_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRejectBatchApiV1BatchesBatchIdRejectPostResponse = zBatchRejectResult;

export const zTriggerMtApiV1BatchesBatchIdTriggerMtPostBody = zBatchTrigger;

export const zTriggerMtApiV1BatchesBatchIdTriggerMtPostPath = z.object({
    batch_id: z.uuid()
});

/**
 * Successful Response
 */
export const zTriggerMtApiV1BatchesBatchIdTriggerMtPostResponse = zBatchTriggerResult;

export const zCreateExportApiV1ExportsPostBody = zExportCreate;

export const zPostPreviewApiV1ImportsPreviewPostBody = zBodyPostPreviewApiV1ImportsPreviewPost;

/**
 * Successful Response
 */
export const zPostPreviewApiV1ImportsPreviewPostResponse = zImportPreviewResponse;

export const zPostCommitApiV1ImportsJobIdCommitPostPath = z.object({
    job_id: z.uuid()
});

export const zPostCommitApiV1ImportsJobIdCommitPostQuery = z.object({
    force_overwrite: z.boolean().optional().default(false)
});

/**
 * Successful Response
 */
export const zPostCommitApiV1ImportsJobIdCommitPostResponse = zImportCommitResponse;

export const zPostRollbackApiV1ImportsJobIdRollbackPostPath = z.object({
    job_id: z.uuid()
});

/**
 * Successful Response
 */
export const zPostRollbackApiV1ImportsJobIdRollbackPostResponse = zImportRollbackResponse;

export const zListKeysApiV1KeysGetQuery = z.object({
    project_id: z.uuid(),
    repository_id: z.uuid().nullish(),
    locale: z.string().nullish(),
    status: zTranslationStatus.nullish(),
    component: z.string().nullish(),
    id: z.array(z.uuid()).nullish(),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Successful Response
 */
export const zListKeysApiV1KeysGetResponse = zListResponseKeyRead;

export const zGetKeyApiV1KeysKeyIdGetPath = z.object({
    key_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetKeyApiV1KeysKeyIdGetResponse = zKeyDetail;

export const zUpdateKeyApiV1KeysKeyIdPatchBody = zKeyUpdate;

export const zUpdateKeyApiV1KeysKeyIdPatchPath = z.object({
    key_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateKeyApiV1KeysKeyIdPatchResponse = zKeyRead;

export const zListScreenshotsApiV1KeysKeyIdScreenshotsGetPath = z.object({
    key_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListScreenshotsApiV1KeysKeyIdScreenshotsGetResponse = zListResponseScreenshotRead;

export const zUploadScreenshotApiV1KeysKeyIdScreenshotsPostBody = zBodyUploadScreenshotApiV1KeysKeyIdScreenshotsPost;

export const zUploadScreenshotApiV1KeysKeyIdScreenshotsPostPath = z.object({
    key_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUploadScreenshotApiV1KeysKeyIdScreenshotsPostResponse = zScreenshotRead;

/**
 * Successful Response
 */
export const zListOrgsApiV1OrganizationsGetResponse = zListResponseOrgRead;

export const zCreateOrgApiV1OrganizationsPostBody = zOrgCreate;

/**
 * Successful Response
 */
export const zCreateOrgApiV1OrganizationsPostResponse = zOrgRead;

export const zDeleteOrgApiV1OrganizationsOrgIdDeletePath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteOrgApiV1OrganizationsOrgIdDeleteResponse = z.void();

export const zGetOrgApiV1OrganizationsOrgIdGetPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetOrgApiV1OrganizationsOrgIdGetResponse = zOrgRead;

export const zUpdateOrgApiV1OrganizationsOrgIdPatchBody = zOrgUpdate;

export const zUpdateOrgApiV1OrganizationsOrgIdPatchPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateOrgApiV1OrganizationsOrgIdPatchResponse = zOrgRead;

export const zListProjectsApiV1OrganizationsOrgIdProjectsGetPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListProjectsApiV1OrganizationsOrgIdProjectsGetResponse = zListResponseProjectRead;

export const zCreateProjectApiV1OrganizationsOrgIdProjectsPostBody = zProjectCreate;

export const zCreateProjectApiV1OrganizationsOrgIdProjectsPostPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateProjectApiV1OrganizationsOrgIdProjectsPostResponse = zProjectRead;

export const zListUsersApiV1OrganizationsOrgIdUsersGetPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListUsersApiV1OrganizationsOrgIdUsersGetResponse = zListResponseUserRead;

export const zCreateUserApiV1OrganizationsOrgIdUsersPostBody = zUserCreate;

export const zCreateUserApiV1OrganizationsOrgIdUsersPostPath = z.object({
    org_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateUserApiV1OrganizationsOrgIdUsersPostResponse = zUserRead;

export const zGetLocaleApiV1OtaProjectSlugLocaleJsonGetPath = z.object({
    project_slug: z.string(),
    locale: z.string()
});

export const zGetLocaleApiV1OtaProjectSlugLocaleJsonGetQuery = z.object({
    platform: z.literal('ios').nullish()
});

export const zDeleteProjectApiV1ProjectsProjectIdDeletePath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteProjectApiV1ProjectsProjectIdDeleteResponse = z.void();

export const zGetProjectApiV1ProjectsProjectIdGetPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProjectApiV1ProjectsProjectIdGetResponse = zProjectRead;

export const zUpdateProjectApiV1ProjectsProjectIdPatchBody = zProjectUpdate;

export const zUpdateProjectApiV1ProjectsProjectIdPatchPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateProjectApiV1ProjectsProjectIdPatchResponse = zProjectRead;

export const zGetProjectAnalyticsApiV1ProjectsProjectIdAnalyticsGetPath = z.object({
    project_id: z.uuid()
});

export const zGetProjectAnalyticsApiV1ProjectsProjectIdAnalyticsGetQuery = z.object({
    window_days: z.int().gte(1).lte(365).optional().default(30)
});

/**
 * Successful Response
 */
export const zGetProjectAnalyticsApiV1ProjectsProjectIdAnalyticsGetResponse = zAnalyticsSummary;

export const zListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListGlossaryTermsApiV1ProjectsProjectIdGlossaryGetResponse = zListResponseGlossaryTermRead;

export const zCreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostBody = zGlossaryTermCreate;

export const zCreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateGlossaryTermApiV1ProjectsProjectIdGlossaryPostResponse = zGlossaryTermRead;

export const zDeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeletePath = z.object({
    project_id: z.uuid(),
    term_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdDeleteResponse = z.void();

export const zGetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetPath = z.object({
    project_id: z.uuid(),
    term_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdGetResponse = zGlossaryTermRead;

export const zUpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchBody = zGlossaryTermUpdate;

export const zUpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchPath = z.object({
    project_id: z.uuid(),
    term_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateGlossaryTermApiV1ProjectsProjectIdGlossaryTermIdPatchResponse = zGlossaryTermRead;

export const zListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListLocaleConfigsApiV1ProjectsProjectIdLocaleConfigsGetResponse = zListResponseLocaleConfigRead;

export const zCreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostBody = zLocaleConfigCreate;

export const zCreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostPath = z.object({
    project_id: z.uuid()
});

export const zCreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostQuery = z.object({
    fan_out: z.boolean().optional().default(false)
});

/**
 * Successful Response
 */
export const zCreateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsPostResponse = zLocaleConfigActivationResult;

export const zDeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeletePath = z.object({
    project_id: z.uuid(),
    config_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdDeleteResponse = z.void();

export const zGetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetPath = z.object({
    project_id: z.uuid(),
    config_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdGetResponse = zLocaleConfigRead;

export const zUpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchBody = zLocaleConfigUpdate;

export const zUpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchPath = z.object({
    project_id: z.uuid(),
    config_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateLocaleConfigApiV1ProjectsProjectIdLocaleConfigsConfigIdPatchResponse = zLocaleConfigRead;

export const zListRepositoriesApiV1ProjectsProjectIdRepositoriesGetPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListRepositoriesApiV1ProjectsProjectIdRepositoriesGetResponse = zListResponseRepositoryRead;

export const zCreateRepositoryApiV1ProjectsProjectIdRepositoriesPostBody = zRepositoryCreate;

export const zCreateRepositoryApiV1ProjectsProjectIdRepositoriesPostPath = z.object({
    project_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateRepositoryApiV1ProjectsProjectIdRepositoriesPostResponse = zRepositoryRead;

export const zDeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeletePath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdDeleteResponse = z.void();

export const zGetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetPath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdGetResponse = zRepositoryRead;

export const zUpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchBody = zRepositoryUpdate;

export const zUpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchPath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateRepositoryApiV1ProjectsProjectIdRepositoriesRepoIdPatchResponse = zRepositoryRead;

export const zTriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostPath = z.object({
    project_id: z.uuid()
});

export const zTriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostQuery = z.object({
    locale: z.string().nullish(),
    status: z.string().optional().default('pending')
});

/**
 * Successful Response
 */
export const zTriggerProjectMtApiV1ProjectsProjectIdTriggerMtPostResponse = zBulkTriggerResult;

export const zTriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostPath = z.object({
    repo_id: z.uuid()
});

export const zTriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostQuery = z.object({
    locale: z.string().nullish()
});

/**
 * Successful Response
 */
export const zTriggerPublicationApiV1PublicationsRepositoriesRepoIdPublishPostResponse = zPublishResult;

export const zPublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostPath = z.object({
    repo_id: z.uuid()
});

export const zPublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostQuery = z.object({
    locale: z.string().nullish()
});

/**
 * Successful Response
 */
export const zPublishToOtaApiV1PublicationsRepositoriesRepoIdPublishToOtaPostResponse = zPublishToOtaResult;

export const zListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetPath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListComponentContextsApiV1RepositoriesRepoIdComponentContextsGetResponse = zListResponseComponentContextRead;

export const zCreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostBody = zComponentContextCreate;

export const zCreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostPath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateComponentContextApiV1RepositoriesRepoIdComponentContextsPostResponse = zComponentContextRead;

export const zDeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeletePath = z.object({
    repo_id: z.uuid(),
    ctx_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdDeleteResponse = z.void();

export const zGetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetPath = z.object({
    repo_id: z.uuid(),
    ctx_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdGetResponse = zComponentContextRead;

export const zUpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchBody = zComponentContextUpdate;

export const zUpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchPath = z.object({
    repo_id: z.uuid(),
    ctx_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateComponentContextApiV1RepositoriesRepoIdComponentContextsCtxIdPatchResponse = zComponentContextRead;

export const zIngestRepositoryApiV1RepositoriesRepoIdIngestPostBody = zIngestRequest;

export const zIngestRepositoryApiV1RepositoriesRepoIdIngestPostPath = z.object({
    repo_id: z.uuid()
});

/**
 * Successful Response
 */
export const zIngestRepositoryApiV1RepositoriesRepoIdIngestPostResponse = zIngestResult;

export const zDeleteScreenshotApiV1ScreenshotsScreenshotIdDeletePath = z.object({
    screenshot_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteScreenshotApiV1ScreenshotsScreenshotIdDeleteResponse = z.void();

export const zGetScreenshotImageApiV1ScreenshotsScreenshotIdImageGetPath = z.object({
    screenshot_id: z.uuid()
});

export const zListTranslationsApiV1TranslationsGetQuery = z.object({
    project_id: z.uuid(),
    locale: z.string().nullish(),
    status: zTranslationStatus.nullish(),
    key_id: z.uuid().nullish(),
    batch_id: z.uuid().nullish(),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Successful Response
 */
export const zListTranslationsApiV1TranslationsGetResponse = zListResponseTranslationRead;

export const zGetTranslationApiV1TranslationsTranslationIdGetPath = z.object({
    translation_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetTranslationApiV1TranslationsTranslationIdGetResponse = zTranslationRead;

export const zUpdateTranslationApiV1TranslationsTranslationIdPatchBody = zTranslationUpdate;

export const zUpdateTranslationApiV1TranslationsTranslationIdPatchPath = z.object({
    translation_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateTranslationApiV1TranslationsTranslationIdPatchResponse = zTranslationRead;

export const zGetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetPath = z.object({
    translation_id: z.uuid()
});

export const zGetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetQuery = z.object({
    limit: z.int().gte(1).lte(500).optional().default(100)
});

/**
 * Successful Response
 */
export const zGetTranslationHistoryApiV1TranslationsTranslationIdHistoryGetResponse = zListResponseTranslationHistoryRead;

export const zReceiveContentfulWebhookApiV1WebhooksContentfulPostHeaders = z.object({
    'x-contentful-webhook-secret': z.string().nullish()
});

/**
 * Successful Response
 */
export const zReceiveContentfulWebhookApiV1WebhooksContentfulPostResponse = zWebhookAck;

export const zReceiveGithubWebhookApiV1WebhooksGithubPostHeaders = z.object({
    'x-hub-signature-256': z.string().nullish()
});

/**
 * Successful Response
 */
export const zReceiveGithubWebhookApiV1WebhooksGithubPostResponse = zWebhookAck;

/**
 * Response Health Health Get
 *
 * Successful Response
 */
export const zHealthHealthGetResponse = z.record(z.string(), z.string());

/**
 * Response Health Scheduler Health Scheduler Get
 *
 * Successful Response
 */
export const zHealthSchedulerHealthSchedulerGetResponse = z.record(z.string(), z.unknown());
